experiment_id: german-ann-lime
app_config:
  secret_file: config/secrets/app-secret.txt
  codebook: config/german/codebook.csv
  templates:
    landing: landing.html
    consent: german/consent.html
    instructions: german/instructions.html
    attention: german/attention.html
    task: german/task.html
    survey: survey.html
    disqualify: disqualify.html
    end: end.html
  attention_data: config/german/german-attention.json
  survey_data: config/german/german-survey.json
db_config:
  overwrite_db: true
  password_file: config/secrets/db-password.txt
  redis_config:
    port: 6666
dataset: german
explainer_config:
  model_type: ann
  model_pretrained: true
  explanation_method: sg
  
